package com.example.android.testing.espresso.screenshotsample

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle

/**
 * A simple [Activity], autogenerated via Studio's 'Empty Activity' wizard.
 */
class MainActivity : AppCompatActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)
  }
}